// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SEM.Infrastructure.Repositories;

#nullable disable

namespace SEM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SEM.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_models_model_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_models_user_id");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("SEM.Entities.PropertyInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readonly");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_property_infos");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_property_infos_model_id");

                    b.ToTable("property_infos", (string)null);
                });

            modelBuilder.Entity("SEM.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SEM.Entities.Model", b =>
                {
                    b.HasOne("SEM.Entities.Model", null)
                        .WithMany("RelatedModels")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("fk_models_models_model_id");

                    b.HasOne("SEM.Entities.User", "User")
                        .WithMany("SavedModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_models_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEM.Entities.PropertyInfo", b =>
                {
                    b.HasOne("SEM.Entities.Model", "Model")
                        .WithMany("Properties")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_infos_models_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("SEM.Entities.Model", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("RelatedModels");
                });

            modelBuilder.Entity("SEM.Entities.User", b =>
                {
                    b.Navigation("SavedModels");
                });
#pragma warning restore 612, 618
        }
    }
}
